- name: Generate {{ haproxy_config_file }} haproxy cfg
  template:
    src: "{{ haproxy_config_template }}"
    dest: "{{ haproxy_config_file }}"
  notify:
    - reload haproxy

- service: name=haproxy state=reloaded
