- include: "setup/{{ ansible_distribution|lower }}.yml"

- name: Update repositories cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install Haproxy
  apt:
    name: haproxy
    install_recommends: no

- service: name=haproxy state=started
